const GET_POST = 'GET_POST';
const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
const GET_POST_FAIL = 'GET_POST_FAIL';

const GET_POST_DETAIL = 'GET_POST_DETAIL';
const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS';
const GET_POST_DETAIL_FAIL = 'GET_POST_DETAIL_FAIL';

export { GET_POST, GET_POST_FAIL, GET_POST_SUCCESS, GET_POST_DETAIL, GET_POST_DETAIL_SUCCESS, GET_POST_DETAIL_FAIL };
